# General Discussion {#general-discussion}

This chapter presents a summary of the research presented in this thesis, followed by its theoretical and methodological implications, and applied implications for Mountain Training and its candidates. I identify future directions for research and discuss the strengths and limitations of the thesis. Finally, this chapter concludes with brief personal reflections.


## Summary of Results {#general-discussion-summary-of-results}

The research presented in this thesis aimed to identify factors that influenced the completion rate of the Mountain Leader qualification. Across the project, I employed a mixed-method approach to collect data from both candidates at various stages in the pathway, and from staff who had an in-depth knowledge of the Mountain Leader process and its candidates. The research presented in this thesis involved six separate but related studies.

Chapter \@ref(ml-qualitative) reported the findings of seven in-depth interviews with Mountain Training Staff and experienced course staff ([Study 1](#ml-qualitative)). The results in this chapter suggest that different factors were important when considering the two main stages of becoming a Mountain Leader (i.e., getting to an assessment and passing). The findings suggest that the candidates who were confident that they could become Mountain Leaders, who had extrinsic participatory motives that were autonomously regulated, who were able to gain experience, and who received appropriate support were the candidates most likely to be assessed. 

The findings indicated that the nature of candidates experience would largely determine their performance at assessment. Candidates who had a variety of relevant experience of the right quality were more likely to pass than candidates who had little relevant experience, little variety in their experience, and low-quality experience. Candidates' experience not only helped them to be more competent through practice but also allowed them to be more confident and resilient.

In Chapter \@ref(ml-pra), I sought to build on the results of [Study 1](#ml-qualitative), by collecting data from candidates about the variables that the findings of [Study 1](#ml-qualitative) suggest are important. Following extensive pilot work to develop an appropriate survey tool (see Appendix \@ref(survey-tool-dev)), the results of pattern recognition analyses in Chapter \@ref(ml-pra) provided evidence of important discriminatory variables for each of the following classification problems: (a) male candidates who were assessed within 18 months of their training course versus those who were not assessed within 18 months ([Study 2](#male-gta)), (b) female candidates who were assessed within 18 months of their training course versus those who were not assessed within 18 months ([Study 3](#female-gta)), and (c) candidates who passed their first assessment versus those who did not pass their first assessment ([Study 4](#ftp)). 

Results from [Study 2](#male-gta) suggested that to get to an assessment within 18 months of training, it was important that male candidates: could fit becoming a Mountain Leader into their lives and prepare for an assessment, were confident in their ability to become Mountain Leaders and their skills, and were able to deal with setbacks they might encounter on the way to becoming a Mountain Leader. 

Results from [Study 3](#female-gta) suggested that to get to an assessment within 18 months of training, it was important that female candidates: could fit becoming a Mountain Leader into their lives and prepare for an assessment, were confident in their skills, had extrinsic participatory motives to become Mountain Leaders, consolidated their experience post-training, and prepared effectively for an assessment by accruing good quality and varied experience. 

Results from [Study 4](#ftp) suggested that it was important that candidates (female and male) received good coaching from training course staff and prepared effectively for an assessment, by gaining experience of suitable quality. 

Taken together, the findings from Studies 2-4 supported those of [Study 1](#ml-qualitative). The congruence of findings across methods and samples allows us to place more confidence in the variables identified as important influences on the completion rate of the Mountain Leader qualification. Accordingly, I can be more confident when making recommendations to Mountain Training based on these findings.

In Chapter \@ref(ml-qualitative) and Chapter \@ref(ml-pra), it was apparent that candidate self-efficacy and experience were important factors in identifying who went onto become Mountain Leaders and who did not. Further, it was also clear that these two factors were linked and there was evidence to suggest that there were gender differences involved in the relationship between experience and self-efficacy. With this in mind, in Chapter \@ref(self-efficacy-qmds), I examined how gender moderated the relationship between experience and self-efficacy. To do so, I used data collected for the work reported in Chapter \@ref(ml-pra) and Appendix \@ref(survey-tool-dev). In [Study 5](study-5), I developed the MLSS to measure self-efficacy for skills related to becoming a Mountain Leader. [Study 6](study-6) had two aims, firstly to confirm the factor structure of the MLSS in a new sample and secondly, to examine the additive and interactive effects of gender and experience on self-efficacy.

The MLSS measures two factors: self-efficacy to perform routine skills and self-efficacy to perform emergency skills. Measurement invariance analyses suggested that the MLSS measured the same factors in female and male candidates; however, there was evidence in [Study 6](study-6) that female and male candidates had different scores on the factors, although the factor structure and item-factor loadings were no differences between genders. In [Study 6](study-6), the results of moderated hierarchical regression analyses suggested that female candidates were less confident than male candidates, candidates with more experience were more confident, and the relationship between experience and routine skill self-efficacy was stronger for female candidates than it was for male candidates.

## Theoretical and Methodological Implications

One implication emanating from the work presented in this thesis is that factors influencing (Mountain Leader) candidate progression and development are multifaceted and complex. As such, there is no “silver bullet” that determines, or even influences, the completion of the Mountain Leader qualification. Accordingly, to positively impact completion rates of the Mountain Leader qualification would require a multifaceted set of changes.

Further, the findings also show that different factors are important at different stages of the Mountain Leader pathway. Therefore, if individuals and/or organisations are trying to improve one step of a training pathway, any changes need to consider the broader picture, so that changes in one area of the pathway enhance as opposed to exacerbating problems later in the pathway. Thus, I recommend that the term “holistic” is viewed as meaning at least multidisciplinary and temporally. This work adds to a body of research from elite sport that recommends researchers take a holistic approach when considering journeys through pathways [e.g., @Jones2019a; @Gullich2019; @Hardy2017]. There are three major theoretical/methodological implications resulting from the work in this thesis, namely a new methodology for researching development pathways, gender differences in the relationship between experience and self-efficacy, and the greater relative importance of good quality and varied experience than the quantity of experience for passing an assessment.

### A Methodology for Researching Development Pathways

The broad methodology used in this thesis provides a framework for those wishing to use a survey approach to examine complex questions in real-world applied environments involving a large number of variables. Despite the plethora of evidence that factors from a range of domains influence training pathways, few researchers have adopted multidisciplinary approaches that are capable of accommodating complex interactions [cf. @Rees2016; @Gullich2019]. Traditionally, due to the limitations of traditional quantitative analyses (e.g., regression-based techniques) doing so has relied on a qualitative methodology [e.g., @Hardy2017]. 

However, with machine learning techniques (e.g., pattern recognition analysis) becoming more readily available a small number of recent studies have used machine learning techniques to adopt a multidisciplinary approach that accommodates the effects of complex interactions [e.g., @Gullich2019; @Jones2019a; @Jones2020]. These studies have relied on interviews to collect data, placing a considerable burden on participants, which has then been coded by the researchers to facilitate quantitative analysis. One reason for using a qualitative approach may be that researchers have felt they were unable to collect valid quantitative data from participants without asking so many questions that they would compromise the quality of their data.

By conducting extensive qualitative and quantitative pilot work (i.e., Chapter \@ref(ml-qualitative) and Appendix \@ref(survey-tool-dev)), I was able to develop a survey tool that collected quantitative data from participants. Using this approach I was able to significantly extend the methodology used by other researchers who have used pattern recognition analyses to understand complex journeys through pathways [e.g., @Jones2019a; @Jones2020; @Gullich2019], where data collection has relied on interview-based methods to collect data. The methodology of this thesis does not necessarily reduce the overall burden on participants; however, it could be viewed as spreading the same total burden over a greater number of participants, through the extensive preliminary work, thereby reducing the burden on each participant. However, if it is important that the pilot work is carried out in exactly the same population, spreading the burden in this way is obviously only possible when there is a large population to collect data from, unlike the populations in the previously cited studies [i.e., @Gullich2019; @Jones2019a; @Jones2020]. The thoughtful researcher will no doubt be able to overcome this limitation.

This preliminary work (reported in Chapter \@ref(ml-qualitative) and Appendix \@ref(survey-tool-dev)) involves a qualitative enquiry coupled with a review of relevant literature to identify potentially relevant factors, finding suitable short-form measures for each factor, and finally ensuring that the resultant survey is of reasonable length,^[What is considered "reasonable" should be determined by the researcher, taking both the research question and population into account.] using empirical methods to reduce the length if necessary. These methodologies supersede methodologies which aim to answer complex questions but can only consider a relatively small number of variables, essentially forcing the researcher to ask relatively simple questions. There will be some situations where interview-based methods are preferable to survey-based methods (e.g., when the population is small, when building a rapport with participants is important, when participants have the time to be interviewed). Therefore I suggest that his methodology provides researchers with another tool for collecting data when researching multidimensional questions (e.g., "Which factors are important in the development of expertise?").


### Gender differences in the Relationship Between Experience and Self-Efficacy

Self-efficacy theory has suggested that performance accomplishments are the strongest influence on efficacy beliefs [@Bandura1982]. Chapters \@ref(ml-qualitative), \@ref(ml-pra), and \@ref(self-efficacy-qmds) all add to the body of evidence that support this [e.g., @Anstiss2018; @Chase2003; @Samson2014; @Shipherd2019]. In Chapters \@ref(ml-qualitative) and \@ref(ml-pra) experience-related variables appeared to be more important for female than male candidates; therefore, I tentatively suggested that the relationship between self-efficacy and experience may not be the same for the two genders considered in this thesis. However, to the best of my knowledge, no published research directly examines *both* the additive and interactive effects of gender and experience on self-efficacy. Therefore, the research reported in Chapter \@ref(self-efficacy-qmds) examined the additive and interactive effects of gender and QMDs (experience) on two factors of Mountain Leader self-efficacy (routine and emergency skills). The results of Study 6 suggested that the relationship between experience and routine skill self-efficacy was stronger for female candidates than it was for male candidates. While the underlying mechanism for this interactive effect was not explored, the implication remains the same; female candidates need more experience than male candidates to feel confident. Whilst this mechanism was not explored directly, the results of Chapters \@ref(ml-qualitative) and \@ref(self-efficacy-qmds) suggest that male candidates are confident even when they have little experience, whereas female candidates are only confident once they have experience.

Given the stronger relationship between experience and routine skill self-efficacy for female candidates, it seems important that they leave the training course with a clear understanding of what they should do to gain more experience. Whereas for male candidates, their development plans may focus more on how to fit the preparation into their lives as a greater number of factors relating to the context of the Mountain Leader qualification within candidates lives were important for discriminating male candidates who were assessed within 18 months of their training course than were important for female candidates.

### Quality and Variety Over Quantity

Deliberate practice theory suggests that higher levels of deliberate practice will result in greater levels of performance [@Ericsson1993]. However, there is evidence that greater levels of experience do not always predict greater levels of performance [see @Rees2016 Section 4.1 for a review]. The results of Chapters \@ref(ml-qualitative) and \@ref(ml-pra) suggest that whilst it is important that candidates have enough experience to meet the prerequisites for passing the Mountain Leader assessment, it is also important that their experience is of sufficient quality and variety. Indeed, there is some evidence that suggests the variety and quality of experience is more important than the quantity of experience, as some candidates with high levels of experience do not pass, whilst some candidates with a lower level of experience do pass.

Skill acquisition literature suggests that improvements in performance are contingent on three factors: the level of challenge, availability of feedback, and the opportunity to detect and correct errors [@Ericsson1993; @Guadagnoll2004]. @Jones2020 found that super-elite cricket batsmen performed more random practice than their elite counterparts and suggested that this greater volume of random practice led to a greater level of challenge and contextual interference and therefore, higher levels of performance. Whilst I did not investigate the relationship between the perceived challenge of candidates' experiences and their performance, it seems likely that having more varied rather than repeated and higher rather than lower quality experience will lead to higher levels of challenge. It is likely that through increasing the level of challenge, higher quality and more varied experience will increase the performance of Mountain Leader candidates. The findings reported in this thesis and those of @Jones2020 suggest that the positive relationship between experience and performance will be stronger for those with more varied experience.


## Applied Implications {#gen-discussion-applied-implications}

The present section proposes some applied implications that may be useful for Mountain Training to consider in addition to those presented in Section \@ref(ml-pra-applied-implications) and Section \@ref(self-efficacy-applied-implications). The implications below relate to the Mountain Leader qualification; however, Mountain Training may also wish to consider them in relation to their other qualifications and other organisations may also consider them relevant to their training pathways. Given that the largest drop-off (in percentages terms) of candidates is in the period between training and assessment and that many of the factors identified as important in this thesis are about what candidates do in that period, the recommendations will focus on this particular period. Some of these implications are relatively simple to act on, whereas others require more work to act upon. Therefore, I present *quick wins*, which represent what I believe to be relatively low-effort interventions and *long-term goals*, which are goals that I believe would take more effort to achieve but would ultimately prove worthwhile.

As mentioned above, both the factors influencing candidates getting to assessment and the factors influencing candidates' assessment performance should be considered together in any intervention designed to increase the completion rate if Mountain Training wishes to have the maximum positive impact on the completion rate of the Mountain Leader qualification. Suppose only factors influencing candidates getting to assessment are considered. In that case, it is possible that there will be an increase in the number of candidates who are not competent enough to pass a Mountain Leader assessment being assessed and thereby reducing the pass rate (e.g., if an intervention that helped candidates gain experience was successful, but did not ensure that experience was of suitable variety and quality).


### Quick Wins

Below are examples of how providing additional information to candidates could provide quick wins for Mountain Training. 

#### Information About the Mountain Leader Qualification.

Providing candidates with more information about the Mountain Leader qualification before or at the point of registration would help candidates understand both the purpose *and* standard of the Mountain Leader qualification. This information would help candidates to make a better-informed decision about the appropriateness of the qualification for their needs. In [Study 1](#ml-qualitative), the findings in Section \@ref(ml-qualitative-gta-understanding-the-standard) suggested it was important that candidates understood "the standard" of the qualification so that they understood how confident they needed to be in their skills. In addition, Section \@ref(ml-qualitative-gta-redirection-lower) suggested that having attended a Mountain Leader training course, staff recommend that some candidates pursue a lower level qualification (e.g., Hill and Moorland Leader) as that would be a more reasonable objective for them than the Mountain Leader qualification. In [Study 2](#male-gta), results indicated that some male candidates might be attending a training course to understand more about the qualification (see Section \@ref(context)) and presumably, having learnt more about the qualification, a proportion of these candidates decide not to continue to assessment. Therefore, I believe that providing this information would help candidates to choose the right course for them, reducing the number of candidates attending a Mountain Leader training course somewhat speculatively and potentially increasing the number of candidates registering for the lower level qualifications. In addition, this information would help candidates understand what they needed to do to become a Mountain Leader which would help them prepare effectively.

#### Information About the Importance of Experience.

Explaining the importance of relevant experience to candidates, but more importantly, how it benefits them, may help candidates to prepare effectively for an assessment. A better understanding of how experience benefits them will allow candidates to plan their consolidation in a way that maximises the benefits of experience. The thesis provides evidence that gaining relevant experience increases candidates' self-efficacy (see Section \@ref(qual-gta-confidence) and [Study 6](#study-6)) and can develop candidates' resilience (see Section \@ref(qual-passing-resilience)). In addition, Section \@ref(ml-qual-pass-exp) describes the importance of this experience being varied and of suitable quality. Explaining the benefits of relevant experience to candidates and helping them to understand how experience provides these benefits should help candidates to make the most of their consolidation. For some candidates, this may result in them doing less, however, their preparation could be more focused, thus making it easier for them to fit preparing for a Mountain Leader assessment into their lives. 

Traditionally Mountain Training has relied on the written word to convey information to candidates. However, the use of new technologies may offer novel ways of providing candidates with information about QMDs in what could be a more engaging format that could also be useful in explaining the nuances of the QMD definition. The advent of the quantified and shareable self through the use of global positioning system (GPS) technology, digital mapping and digital media provides the opportunity to show candidates examples of QMDs overlaid on a digital topographical map^[This link provides an example of a route being overlaid on a digital map, albeit a bike ride on the road https://www.relive.cc/view/vJOKXWoyK56] and at important junctures throughout the day, brief segments of video could be used to explain what about that juncture means that it counts as a QMD. Indeed, it would also be possible to discuss changes to the day that would have meant it was not a QMD (e.g., walking up an established path in good weather with peers verses walking up the same path, but in poor weather whilst looking after a group of novices).


### Long Term Goals

Long term goals based on the findings from the thesis for Mountain Training could include: (a) developing a system for creating individualised consolidation plans for candidates who have been trained, (b) identifying candidates who lack confidence, either at the end of their training course or during their consolidation, and then offering individualised support to bolster their confidence, and (c) using CMS to introduce candidates who may benefit from meeting other candidates (e.g., to prepare together). Each of these goals would aim to help candidates to make the most of their consolidation period. Therefore, these three goals should help Mountain Training increase the proportion of candidates who have attended a Mountain Leader training course who subsequently become Mountain Leaders.


#### Development Plans.

In [Study 1](#ml-qualitative), participants explained that they felt it was important candidates left their training course with a good understanding of what they---as an individual---needed to do to prepare for an assessment and lack of time was identified as a barrier to gaining enough experience to be assessed. Furthermore, in Chapter \@ref(ml-pra) female and male candidates who were not assessed within 18 months of their training course were identified as more likely than candidates who were assessed within 18 months of their training course to report that becoming a Mountain Leader was less important than other life goals and they were also more likely to report that they did not have enough time to become a Mountain Leader. In [Study 1](#ml-qualitative), participants suggested that the variety and quality of a candidate's experience are more important than the quantity of experience to the outcome of their assessment. This point was supported by the results of Study 4 (Section \@ref(ftp-results)), which identified that candidates who included experience below rather the standard for the Mountain Leader qualification in their logbook rather than those did not were less likely to pass. In addition, candidates who included experience above the standard for the Mountain Leader qualification in their logbook rather than those who did not were more likely to pass. 

Considering these findings in combination, it seems that time is a precious resource for Mountain Leader candidates and that helping them to make the most of the time they have available is extremely important. I suggest that ensuring candidates leave their training course with a written development plan for their consolidation that describes how, within the context of their life, they can best prepare for an assessment. This would help candidates prepare *effectively and efficiently* for an assessment, thus increasing the completion rate of the Mountain Leader qualification. Goal setting theory would suggest that these plans should: include short- and long-term goals; include a combination of outcome, performance, and process goals; consider the individual situation and needs of the candidate; have the opportunity for feedback on goal progress; have review points scheduled (either by time or event); and importantly should have input from both the candidates and training course staff [cf. @Gould2005; @Weinberg2014]. 

#### Course Staff Training.

The staff on a Mountain Leader training course are in a position to have a significant impact on a candidate’s journey through the pathway. Chapters \@ref(ml-qualitative) and \@ref(ml-pra) both discuss staff behaviours that can positively influence candidates (e.g.,  through goal setting and fostering autonomous motivation). Further, research suggests that by training those in leadership positions (e.g., course staff) it is possible to improve their leadership behaviours and subsequently their followers' self-confidence, resilience, satisfaction, and their likelihood of completing a training pathway [cf. @Hardy2010]. Therefore, it would seem prudent to provide training to Mountain Training course staff, informed by this research, to develop their coaching skills to maximise the positive impact that they can have on candidates' journeys through the Mountain Leader pathway. @Wagstaff2018 describe five coaching skills---observation, questioning, goal setting, developmental feedback, and motivational feedback---which provide a useful framework for such training as they are easily understood, and there is a degree of overlap with other theories (e.g., transformational leadership, basic psychological need support).

#### Reviewing Assessment Prerequisites.

The results presented in this thesis suggest that difficulty gaining experience is one of the main barriers to candidates becoming Mountain Leaders. The main prerequisite for assessment related to candidates' experience is the number of QMDs. More specifically, Mountain Training states, "You must have logged a minimum of 40 Quality Mountain Days in three different regions of the UK and Ireland" [@MTUK2015a, p 6]. However, results of Study 1 suggest that quality and variety seem to be more important than the quantity of QMDs and that some candidates were competent despite having fewer than 40 QMDs (Section \@ref(ml-qual-pass-exp)). Further, in Study 4, I discussed the fact that the only reason that `r papaja::printnum(100*7/23)`% of candidates in the analysis did not pass their first assessment was that they had too few QMDs (Section \@ref(study-4-preparation-for-assessment)). 

Based on these findings, Mountain Training may wish to review their prerequisites for attending an assessment course. It is possible that providing prerequisites that were more prescriptive about the quality and variety of experience would allow the quantity of QMDs required to be reduced, thereby making it a more attainable goal for some. Given the importance of candidates knowing what they need to do to prepare for a Mountain Leader assessment, more prescriptive prerequisites may also help candidates prepare effectively for an assessment. However, this suggestion should be taken as just that, a suggestion. Conducting the interviews and being embedded with Mountain Training for the best part of four years has given me an understanding of QMDs and the perception of them by the Mountain Training network (e.g., staff, providers). The breadth of the definition is somewhat deliberate, allowing it to be interpreted differently---by both candidates, course staff, and Mountain Training---to accommodate the wide ranges of experience that different candidates will have. There is a perception amongst the Mountain Training network that candidates will appreciate this breadth once they have gone through the process of becoming a Mountain Leader. Whilst I appreciate this sentiment, the "when you know, you know" approach is not necessarily helpful to candidates who are trying to prepare for an assessment.

The current concept and definition of QMDs are extremely important to Mountain Training; however, candidates do not always understand the concept or definition of QMDs. In addition, many candidates struggle to accrue the prerequisite experience to attend an assessment course---40 QMDs---and therefore do no get to assessment. However, there is evidence that some candidates are capable of successfully completing the practical element of an assessment course with fewer than 40 QMDs. Further, it is clear that what candidates do doing their preparation for assessment is more important than the number of QMDs they have is when considering assessment performance.

Given the importance of candidates understanding what they need to do to prepare effectively for an assessment and the overarching aim of this research project (i.e., to find ways in which Mountain Training can improve the completion rates of the Mountain Leader qualification) Mountain Training could consider, or even pilot, an alternate set of experience-based criteria for attending an assessment. Given the greater relative importance of variety and quality of experience, this alternate set of criteria could reduce the quantity criterion, thus making it more attainable for those with limited time available to prepare for an assessment but provide more specific criteria for the quality and variety of this experience. 

For example, candidates may need to gain additional experience after their training course that includes three graded scrambles, evidenced experience of navigating "off the beaten track," and evidenced experience in bad weather. Further, they may be required to gain this experience in at least two of the main mountainous regions (i.e., Scottish Highlands, the Lake District, the Mourne Mountains, and Snowdonia). If this additional experience were to be set at 10 days in total, it means that a candidate who could spend five days a year gaining QMDs would be able to get from training to assessment in two years, rather than four. As shown in Figure \@ref(fig:survival-sex), the likelihood of a candidate being assessed four years post-training is much lower than the likelihood of them being assessed two years post-training.

It is important to note that this suggestion is meant to increase the proportion of candidates who become Mountain Leaders having attended a training course and is not meant to lower the standard of candidates who get to assessment. To borrow a phrase from a similar stream of research, this is meant to "train [candidates] in, not select out" [@Hardy2014d]. 

Therefore, to test the efficacy of this suggestion, Mountain Training should pilot the alternate criteria alongside the current ones, thereby offering two routes to assessment. This approach would allow them to observe the proportion of candidates who get to an assessment via each route, which would show if the new criteria did make assessment more accessible. It would also allow Mountain Training to monitor the pass rate for candidates, as it may be important to ensure that the overall pass rate did not decrease and to ensure that candidates who got to assessment via the new criteria were suitable prepared and experienced for assessment.


#### Supporting Access to the Mountains.

A barrier to completion identified in \@ref(qual-gta-gaining-experience) was living further away from the mountains (Section \@ref(qual-gta-location)). Travel time to the mountains was an important feature for discriminating candidates who passed their first assessment from those who did not, and I suggested that living further from the mountains was a reason for some candidates logging experience below the standard of the Mountain Leader qualification. As previously discussed, experience below the standard is unlikely to prepare candidates for a Mountain Leader assessment effectively. Therefore, identifying and supporting candidates who have difficulty accessing the mountains may help them to gain enough experience of sufficient quality to become Mountain Leaders. 

This support could be provided at two levels. Firstly, direct support could be offered to candidates who are registered for the Mountain Leader qualification if they are identified as having difficulty accessing the mountains. If these candidates are geographically dispersed, then travel bursaries may help them to join up public transport links with more expensive forms of transport (e.g., taxis). However, if these candidates are located near one another, it might be possible to try and develop a community transport system. Secondly, if there are candidates who have difficulty accessing the mountains, it is likely that there are other people, including those who are not registered for the Mountain Leader qualification, who also find it difficult to access the mountains. Therefore, identifying the latent demand for access to the mountains and improving the travel provision to the mountains may have a greater positive impact than just helping candidates to become Mountain Leaders.


#### Changes to DLOG.

This implication is somewhat speculative, but given that the causal attributions made by a candidate about their experience are likely to influence the change in efficacy that results from the experience, trying to influence these causal attributions may reduce the negative impact that experiences perceived as failures have on self-efficacy and increase the positive influences of success [cf. @Rees2005]. Mountain Training's DLOG facility provides an interesting opportunity to do just this. Candidates could be required to provide information about their experience, additional to that already required, to encourage them to frame the experience in a positive manner. For example, @Seligman2005 showed that an online intervention that required participants to write three good things about their day for a week along with their perceived causal attributions for each good thing increased happiness and decreased depressive symptoms for six months. Therefore, it is conceivable that asking candidates to write three good things about the experience they are logging, and their causal attributions could help candidates frame their experiences in a positive manner.


## Strengths and Limitations {#general-discussion-strenghts-limitations}

### Strengths {#general-discussion-strengths}

There are several strengths to this thesis. Firstly, it is the first investigation into the completion rates of the Mountain Leader qualification and did so in a holistic manner, making use of various existing bodies of research in conjunction with the domain-specific knowledge of Mountain Training and the research team. The methodology provided a rigorous investigation and this approach has resulted in robust findings. More specifically, the multi-source mixed-methods approach allowed us to triangulate the findings between the studies reported in this thesis, as well as explore the nuances of the data. In addition, the state-of-the-art statistical techniques used in data-analysis have allowed this research to overcome the limitations of the traditional linear analytical approaches normally applied to similar research. Further, this thesis is based on a significant quantity of both qualitative and quantitative primary data. As mentioned above, the congruence of the qualitative and quantitative data supports the generalisation of this thesis' findings to the wider Mountain Leader population.

### Limitations {#general-discussion-limitations}

The main limitation of this thesis is that most of the work relies on retrospective methods, thus making the designs weak with regard to causality. However, collecting data from multiple sources allowed us to triangulate the findings, additional confirmatory and prospective analyses in Chapter \@ref(ml-pra) supported the findings of the main analyses, and importantly, the interpretation of results has been theoretically driven. It should, however, be noted that these interpretations reflect my understanding of psychology and that there are likely other  plausible explanations for the results reported. @Box1976 stated that "All models are wrong" and suggested that scientist should seek "simple but evocative models" and "be alert to what is importantly wrong." I would suggest that the models presented in this thesis are simple and evocative, in that they resonate with both the research team and Mountain Training, and I do not believe them to be "importantly wrong." A related limitation is the lack of any intervention or experimental studies. Either an intervention or experimental study would have been beneficial for validating the findings reported in this thesis and would have been beneficial for developing a broad research experience. However, the development and use of the methodology in this thesis have allowed me to develop a wide range of skills, most notably the use of advanced and complex statistical analyses, survey design, and dissemination to non-academic audiences.

A final noteworthy limitation is the representativeness of candidates who provided data for this project. As discussed in Chapter \@ref(ml-pra), retrospective responses to the survey were not representative of the wider populations. Candidates who had not been assessed or who had not passed their first assessment were less likely to respond to the survey. The nature of most research is similar, in that it is not always possible to collect data from everyone that one would like to. However, it is significant that the survey which collected data for Chapter \@ref(ml-pra) included data from 15.35% of the population who met the inclusion criteria. Thus, even if this thesis were only relevant to 15.35% of the candidates, it would be noteworthy. Furthermore, the results of Chapter \@ref(ml-qualitative) support those of Chapters \@ref(ml-pra) and \@ref(self-efficacy-qmds), therefore I believe that it is highly likely that the findings are generalisable beyond the 15.35% despite the bias of the sample towards those who are assessed and do pass.

### Future Research Directions

Two main directions for future research are discussed in Section \@ref(ml-pra-future-directions) and Section \@ref(chapter-4-future-directions). For the sake of completeness, they are briefly highlighted again here. Following that, I briefly suggest two additional future directions for research that are based on the findings of the thesis, rather than a single chapter.

Firstly, further analysis of the data collected in Chapter \@ref(ml-pra) would mitigate the effects of sampling and attribution bias, as there would be a greater number of responses from candidates who responded to the survey prospectively. The benefit of this would be the increased confidence that I could place in the findings as a result of the prospective nature of the analysis.

Secondly, a more detailed investigation into the effects of experience on self-efficacy for females and males should be completed. This investigation should include other relevant variables (e.g., perception of the experience, attributions, personality) and should be conducted with both a longitudinal and experimental design (not necessarily in the same study). This would benefit Mountain Training as they could then provide gender-specific advice to candidates about increasing efficacy. Indeed, such a study would be of great interest to the applied psychology community as it would be the first study of its kind, providing new knowledge to the scientific community and developing self-efficacy theory.

In addition to these directions for further research, it would seem prudent for Mountain Training to consider what factors are important for the completion of other Mountain Training qualifications, given that candidate drop-off is similar for all qualifications (see Figure \@ref(fig:qual-pathway-drop-off-plot)). Understanding which factors are similar for other qualifications, says something about the generic training pathway and which factors are different would tell us something about developing different levels of expertise/performance and would therefore be of interest to both Mountain Training and the wider community of researchers and practitioners.

Finally, it would be prudent to investigate the efficacy of any intervention based on the implications listed above. If such interventions were shown to be effective, it would lend support to the explanations provided in this thesis. Results that did not support the explanations presented in this thesis would also prove interesting, as they would challenge well-established psychology literature (e.g., self-efficacy theory).


## Conclusion {#general-discussion-conclusion}

The conclusions of this research can be presented in a relatively simple manner; Mountain Training's Mountain Leader qualification pathway is effective and candidates who want to become Mountain Leaders and can fit the preparation into their life will achieve their goal, whilst those who do not or cannot, will not achieve theirs. However, this thesis highlights the importance of the consolidation period for candidates and provides some evidence-based recommendations for ways that Mountain Training could provide additional support to candidates, to increase the completion rate without reducing the standard of Mountain Leaders.
