# Mountain Training Executive Officer Interview Guide {#appendix-interview-guide}

## Interview A

Thank you for agreeing to be interviewed today. The information that I sent you earlier outlined five themes to cover over the two interviews; during this interview, I would like to cover four of them: Candidate Background, Candidate Career History, Social Influence, and Personal Characteristics.

As the purpose of these interviews is to understand which factors differentiate those who do become Mountain Leaders from those who do not, I will ask you about “completion”. Someone who “completes” is someone who has passed a Mountain Leader assessment. However, I am interested in more than just who passes their assessment and who does not. Those who do not complete, may have attended been assessed but not passed; been trained or not assessed; or even registered and not trained.

At this early stage of the project it is important that we cover as many different variables as possible. As such, some of the things I ask you about may not seem immediately relevant to completion of the Mountain Leader award, or may seem very similar to other questions that I have asked. It would be much appreciated if you would answer each question as well as you can.

This interview should last between 2 and 3 hours, there is a break scheduled into it. As stated on the information sheets I will be recording the interview, I will also write some things down during the interview for me to refer back to, please don’t let this distract you. 

One of the challenges of working with a small group of participants is ensuring that their confidentiality is preserved. Holding a public position can make maintaining confidentiality more challenging. I have considered this issue and various ways of overcoming this challenge at great length and intend to work closely with you to reach the highest levels of confidentiality possible. You have already read and signed the confidentiality and consent agreements prior to this meeting, which outline the process for maintaining confidentiality. I would however like to reiterate that you will be given opportunities, throughout the process, to review the information you have provided and raise any concerns you may have. 

Stop me at any point if you would like a break and please ask for clarification if anything is not clear. 


### Candidate Background.

I’m going to start by asking you some questions about the Mountain Leader candidates who attend courses in your region to develop an idea of who they are and where they come from. I make no assumptions about what is “good” or “bad” with regards to becoming a Mountain Leader, so there are certainly no “right” or “wrong” answers. Whatever you say in this interview is between you and the research team, I would like you to speak freely about the Mountain Leader award and its candidates in your region.

* Could you start by describing a typical group of six candidates on a Mountain Leader training course to me?
* Can you give me some examples of the types of people who are always candidates who you will always see on a Mountain Leader award course in your region?
  * Prompt: Age, sex, location, ethnicity, socio-economic
* Can you give me some examples of other candidates who you see on Mountain Leader award courses in your region?
  * Prompt: Age, sex, location, ethnicity, socio-economic
  * …and do these candidates go on to become mountain leaders?
* Are there any types of people who are notably absent from Mountain Leader award courses in your region? 
  * Prompt: Age, sex, location, ethnicity socio-economic
* Does the make up of an assessment course looks the same? If not, how does it vary?
  * Are there any differences in the numbers of men and women on training and assessment courses? If so, why do you think that is?
  * Are completion rates for men and women the same? If not, why do you think that is?
* How, if at all, do you think that a candidate’s age at registration affects their progression through the Mountain Leader award?
  * What is it about being older or younger that makes a difference?
  * Is there a difference in the time it takes for an older or younger candidate to become a Mountain Leader? If so, why do you think that is?
* We’ve spoken about how a candidate’s age at registration might influence their chances of completion, now, could you tell me a little bit about how life experience at registration might affect candidates’ chances of completion?
  * Prompt: positively or negatively
* Are there are any professions that significantly influence, positively or negatively, completion of the Mountain Leader award?
  * What do you think it is about these professions that makes a difference here?
    * Prompt: Time, money, relatedness, soft skills, dealing with large groups of diverse people (teachers, coaches, youth leaders etc.), doing work in difficult situations (e.g., A&E doc/nurse/teacher)
* Is there anything about candidates’ backgrounds that you think is important but we haven’t spoken about? 
* We have spoken about a number of different factors relating to candidate background. Do you think that there any factors relating to candidate background that are generally more important with regards to completion of the Mountain Leader award?


### Candidate Career History and Social Influence.

I would like to find out a little bit more about the Mountain Leader candidates in your region; what has led them to the Mountain Leader award, why they might be interested in it, and what they might do with the award.


#### Motives/Motivation.

* Could you give me some examples of the types of reasons that people have given for wanting to become a Mountain Leader?
  * Prompt: to develop their personal skills/to become an instructor. Taking family & friends out/working, scouting
* How, if at all, do you think that these different motives have affected candidates’ chances of becoming a Mountain Leader?
  * Prompt: doing it as a means to an end; doing it because they love being outdoors
  * Prompt: …and what about candidates who are enrolled on an “outdoor degree”/centre trainee/fast-track scheme?

#### Intentions/Expectations.

* Could you give me some examples of different time scales that candidates expect to become Mountain Leaders in?
  * …so, you have mentioned that some people expect to complete quite quickly while others expect it to take a long time; why do you think that there are these differences?
  * How often, if at all, do you see discrepancies between people’s expectations and reality?
  * How, if at all, does the time scale a candidate expects to become a Mountain Leader in affect their chances of completion?

We have just been discussing some of the reasons that people want to become Mountain Leaders and how long they think it will take them. Now I would like to find out how hopeful Mountain Leaders view their future career.

* What do candidates think working as a Mountain Leader will be like?
* Which candidates’ expectations are the closest to reality?
  * …and whose are the furthest from reality?
* Why do you think these discrepancies exist?
* How do these discrepancies affect a candidate’s chances of becoming a Mountain Leader?
* Could you give me some examples of how different candidates might see the Mountain Leader award fitting into their working lives?
  * Long- vs. short- term career?
  * ML only or aspirations to hold higher awards?
  * Wholly- vs. partly- in the mountains?
  * Interactions between the 3


* Some candidates will see themselves working wholly in the mountains once they become Mountain Leaders, whereas others won’t could you tell me a little bit about the differences you see in these candidates?
  * Can you give me some examples of the types of people who see themselves as working wholly in the mountains?
    * Which of these candidates do you think expect that working in the mountains will be a long-term career for them?
    * …and which of the see it as a shorter-term career?
    * Do these candidates see the Mountain Leader award as a stepping stone to higher awards (e.g., MIA or IML) or, do they see becoming Mountain Leaders as their ultimate goal?
    * Do you see any differences in the expectations of older and younger candidates with regard to their future careers being wholly or partly in the mountains?
  * …and can you give me some examples of candidates who see themselves as working partly in the mountains and partly elsewhere?
    * Which of these candidates do you think expect that working in the mountains will be a long-term career for them?
    * …and which of the see it as a shorter-term career?
    * Do these candidates aspire to hold higher level awards, or do the only want to become Mountain Leaders?
  * Do you feel that candidates who only want to become Mountain Leaders try to complete the award quickly so that they can start working, or do they take their time as they feel that there is no rush?
  * Do you feel that candidates with aspirations for higher awards present themselves for an assessment before they are ready to try and move along up the qualification ladder, or do they present well prepared in an effort to be efficient with their time?
* Do you think that candidates who see outdoor instruction as being their main source of income and aspire to holding higher level awards are different from those who see out door instruction as their main source of income but do not aspire to hold higher level awards?
  * What do you think the difference is here?
* Are there people who have these higher aspirations, but don’t see outdoor instruction as their only source of income?
  * Could you tell me a little bit about these people?
* We have spoken a little bit about the different views and expectations candidates might hold; how, if at all, do you think that these expectations affect a candidate’s progression through the Mountain Leader award?
  * Prompt: who become Mountain Leaders? & Time to completion
    * What do you think is different here?
* Have you ever seen a candidate’s end goal change as they progress through the Mountain Leader pathway? If so, what changed and why do you think that was?
  * Can you give me some examples of the types of people whose end goal has changed?
    * Have you ever seen the opposite?
  * What effect do you think that these changes have on a candidate’s chance of completion?
Relevant work experience
* Could you tell me about the opportunities available in your region to candidates for relevant work, paid or unpaid, prior to their ML assessment, if there are any?
  * Do you think any of these opportunities more useful to candidates than others? If so, which ones do you think are the most useful?
  * …and which ones do you think are the least useful?
  * Are any of these opportunities unhelpful to candidates? If so, which ones are these and why do you think that is?
* Could you give me some examples of the types of candidates who make use of these opportunities?


#### Critical Developmental Events.

Sometimes, an event in our lives can change our views or may present us with an opportunity for change. This could be something as extreme as losing one’s job or, in a less extreme example, this might be spending a day in the outdoors with family, friends or an inspiring instructor. These events are sometimes called “critical developmental events”.

* How many candidates, if any, attend training courses following something that could be described as a “critical developmental event”?
* Some of these events might instigate more permanent motivation than others, could you give me some examples of events that has provided candidates with strong but short motivation?
* …and could you give me some examples where perhaps it has been a factor in enduring motivation for candidates?
* How, if at all, do you think that critical developmental events influence candidates?
  * Positive or negative
  * Same for all candidates?
  * Why do you think that might be?


#### Other Qualifications.

* Some candidates will be registered for other sporting qualifications, both with Mountain Training and other organisations; how, if at all, does being registered for more than one qualification affect a candidate’s chances of becoming a Mountain Leader?
* Which other qualifications, if any, seem to have the greatest impact on a candidate’s chances of becoming a Mountain Leader? 
  * Prompt: positive or negative; make them comfortable in the mountains, managing groups; leaves them with little free time; decision making; leadership
* Some candidates will be working towards non-sporting qualifications e.g., a degree or an NVQ. How, if at all, do you think that working towards a non-sporting qualification influences a candidate’s chances of completion?
  * Could you give me some examples of candidates who have benefited from working towards a non-sporting qualification at the same time as working towards their Mountain Leader Award?
  * …and could you give me some examples of candidates who have been adversely affected by working towards a non-sporting qualification at the same time?
* Which influences a candidate’s chance of completion more, being registered for another Mountain Training qualification, a qualification in another sport (e.g., mountain biking, paddling or mainstream sports) or a non-sporting qualification?
  * …and why do you think that is?


#### Subjective Norms/Social Influence.

We are all involved in different social groups and have different places in them, creating our own “social norms.” I would just like to reiterate that I make no assumptions about what is “good” or “bad” with regards to factors that may or may not influence candidates’ completion of the Mountain Leader Award.

* Have you observed that people who come from certain social groups fair better on ML courses than people from other social groups? E.g., candidates whose families or friends regularly engage with the mountains? Candidates from inner cities vs.rural areas? Candidates who are sporty vs.those who are less sporty?
  * What is it about those social groups that you think might make those differences?
* Can you give me some examples of social groups that candidates who attend training but not assessment have come from?
  * One definition of a social group is, “two or more people who interact with one another, share similar characteristics, and collectively have a sense of unity”
  * Could you tell me how, if at all, these social groups influenced candidates?
    * Prompt: positively or negatively?
    * Attraction to outdoor- vs. everyday-life
* Are there any social groups that are noticeably absent from Mountain Leader courses? If so, which ones?
* How important, if at all, is it for a candidate to feel that they have people around them who understand why they want to be a Mountain Leader?
* How, if at all, does the sense of being different from other people influence a candidate’s chance of completion?
* How important, if at all, is it for candidates to spend time in the mountains with people from their social groups?


#### Relevant Media Influence.

Candidates will not only be influenced by the people they spend time with but also by the things that they read, see, and hear.

* Could you give me some examples of the types of candidate that have been influenced by the things that they have read, watched or heard?
  * Prompt: positive or negative influence
  * Prompt: UKC/H, Trail magazine, The Professional Mountaineer, MT’s website
* Which candidates, if any, do you think are more likely to be influenced than others? Why do you think that is?
We are all aware that social media has become an increasingly important and useful part of day-to-day life. 
* Please would you tell me a little bit about how candidates use social media in relation to the Mountain Leader award?
* Could you give me some examples of candidates and how they have been helped by social media?
* Could you give me some examples of social media helping candidates?
* …and can you give me some examples of candidates being negatively influenced but social media?
* Which candidates, if any, does social media have the greatest impact on? 
* Have you noticed any social media groups that appear to be particularly influential? This can be in a positive or negative way.


#### Role Models

* Role models can be both positive and negative (i.e., I want to be like him/her and I don’t want to be like him/her). How important do you feel that role models, positive or negative, are to candidates in your region?
* Could you give me some examples of positive role models and their influence on candidates?
  * Prompt: which candidates, time to completion
* Could you give me some examples of negative role models and their influence on candidates?
  * Prompt: which candidates, time to completion
* Do some candidates identify with role models more easily than others?
  * Do you think that it is something about the candidates or the role models that makes it easier to identify with them? 
  * What do you think that is?
* Is there anything about candidates’ career history or social influence that you think is important but we haven’t spoken about?
* We have spoken about a number of different factors relating to candidate career history and social influence. Do you think that there any factors relating to candidate career history or social influence that are generally more important with regards to completion of the Mountain Leader award?

### Personal Characteristics.

#### Attitudes/Outcome Expectations.

Now I would like to talk to you a little bit about attitudes and outcome expectations towards Mountain Leader training courses.

* Could you describe some of the attitudes displayed by candidates towards the training course?
  * How, if at all, do these attitudes change over the week?
    * Why do you think that was?
* Could you give me some examples of the type of candidate who attends a training course but have no intention of booking an assessment?
  * Why do you think that these candidates come on a training course?
  * Do any of these candidates go onto assessment? Why do you think that is?
  * Have you ever seen this change over time? If so, what changed their mind?

And now I would like you to tell me about candidates’ attitudes and outcome expectations on assessment courses.

* Could you describe some of the attitudes displayed by candidates towards their assessment?
  * How, if at all, do these attitudes change over the week?
    * Why do you think that was?
* Could you give me some examples of the types of candidate who are confident that they will pass, when they arrive for their assessment?
  * What do you think it is about these people that make them think that they are going to pass?
  * …and how did they do?
* …and, could you give me some examples of the types of candidate who are not confident that they will pass, when they arrived for their assessment?
  * What do you think it is about these people that make them think that they are not going to pass?
  * …and how did they do?
* What do you think is different here between those who do expect to pass and those that don’t?
* To what extent do candidates see the assessment as a holistic process?
  * …and what effect does this have on their chances of completion?
* Do you see any differences in the attitudes towards assessment between candidates who have received an exemption from training and those who have been on a training course?
  * Do you think it is obvious on an assessment who has received an exemption from training?


#### Self-efficacy.

* To what extent do candidates in your region feel that they have the necessary resources to become Mountain Leaders?
  * How, if at all, do you think this changes over time? 
    * Do you think that is that the same for all candidates?
  * How do you think that the ML process facilitates this belief?
    * …again, do you think that is the same for all candidates?
  * And can you give me any other examples of things that facilitate a candidate’s belief that they can become a Mountain Leader?
  * Could you give me some examples of obstacles that prevent candidates believing that they are able to become Mountain Leaders?


#### Mastery Aspirations.

Some candidates will want to be the best that they can be, some will want to be good enough to pass, whilst some will want to be better than the people around them.

* Could you give me some examples of the types of candidate who wants to be the best that they can?
* Could you give me some examples of the types of candidate who just want to be good enough to pass?
* What differences, if any, do you think there are there between those who want to achieve the required standard and those who want to be as good as they can be?
* …and can you give me some examples of the types of candidate who want to be better than the other people around them?
* Do you feel that there are any candidates who see an element of competition in the Mountain Leader award? This could be with other candidates, or with people in their day to day lives.
  * Could you give me some examples of the types of candidate who holds these competitive views?
  * What differences, if any, do you see between these candidates and those who don’t see any element of completion in the Mountain Leader award?
  * How, if at all, do you think these differences affect candidates’ chances of becoming Mountain Leaders?
* How, if at all, do you think that candidates who compare themselves to other candidates benefit from this?
* …and how, if at all, do you think that this is detrimental?
* What effect, if any, do you think that comparing to others on a candidate's chances of completion?
* How, if at all, do you think that the “overall strength” of candidates on a course will affect individual candidates?
  * Do you think that “strong cohorts” to inspire weaker candidates, or are they more likely to discourage them?
    * What, if any, differences do you see with stronger candidates?
  * …and what about “weak cohorts”? Do you think that they might affect a stronger candidate?
* How else do you think that the other candidates on a course might affect candidates?
  * Prompt: completion?


#### Disconfirmatory Experiences.

A disconfirmatory event is one that causes an individual to question their belief in something, sometimes their own abilities.

* Could you give me some examples of disconfirmatory experiences in your region?
  * Prompt: In relation to people, bad days out on the hill
* How common it is for candidates to have disconfirmatory experiences?
* How are candidates affected by these experiences?
  * Prompt: Do they motivate them to prove the person wrong or does it lower their confidence?
* Which candidates, if any, are better at dealing with these experiences than others? 
* How, if at all, do disconfirmatory experiences affect a candidate’s chances of completion?


#### Resilience & Robustness.

Candidates will need to deal with stressful events, both in the mountains and also in their normal lives. Disconfirmatory experiences could be an example of a stressful event, but there will be many others.

* Some candidates’ self-confidence will be knocked by these stressful events, whilst others won’t be. What differences do you see between these two groups?
  * Could you give me some examples of the types of candidate whose self-confidence would not be affected?
  * …and could you give me some example of those whose self-confidence would be knocked?
Some of those who have had their self-confidence knocked will be better at “bouncing back” from this than others.
* Could you give me some examples of candidates who are better at bouncing back from stressful events that others?
  * …and can you give me some examples of candidates who are less good at bouncing back from stressful events?
  * What is different here?
* When considering who does and who doesn’t become a Mountain Leader, which seems more important: the ability to maintain self-confidence or the ability regain self-confidence if it has been knocked? 
* Could you explain to me which affects a candidate’s chance of completion more: the number of stressful events that they encounter or their ability to deal with these events?
* Is there anything about candidates’ personal characteristics that you think is important but we haven’t spoken about?
* We have spoken about a number of different factors relating to candidate’s personal characteristics. Do you think that there any factors relating to a candidate’s personal characteristics that are generally more important with regards to completion of the Mountain Leader award?

#### End.

* Is there anything in relation to: Candidate Background, Candidate Career History, Social Influence or Personal Characteristics that we have not covered but you think is relevant to completing the Mountain Leader Award?
* Thank you for your time today.
* Next time I would like to talk to you about candidate’s personal ability and also the support that candidates in your region receive.


## Interview B

Last time we talked about: Candidate Background, Candidate Career History, Social Influence and the Personal Characteristics of candidates. In this part of the study I would like to ask you some questions about Candidate Ability and Candidate Support. Like last time, this interview should take two to three hours and has a break scheduled into it but stop me at any point if you would like another break.

I would like to reiterate that, I make no assumptions about what is “good” or “bad” with regards to becoming a Mountain Leader, so there are certainly no “right” or “wrong” answers. I would like you to speak freely, whatever you say in this interview is between you and the research team.

Like last time I will be recording the interview, please ask for clarification if anything is not clear.

Is there anything that you would like to go over before we start? Maybe something you would like to recap or something that you have thought of since the last interview? 


### Candidate Experience & Ability.

Now that I have an idea of who candidates are, where they come from, and what it is that has brought them to you; I would like you to tell me about the ranges of candidates’ experiences and how good they are at judging their own abilities.  


#### Personal Experience.

Candidates will have a variety of experience in the outdoors. I’m sure that there are some candidates who turn up to their assessment with 40 Quality Mountain Days and I am sure that there are others who turn up with twice or even three times that. As well as varying in depth of experience, candidates also vary in the breadth of their experiences.  Some will only have experience that falls within the ML remit and others will have a greater breadth of experience in the mountains (i.e., experience that falls outside of the ML remit, this could be in summer or winter). 

* Can you tell me how, if at all, you think a candidate’s experience in the mountains affects his/her chances passing their assessment?
  * What about this experience has the greatest influence on a candidate’s chances of completion?
* Could you give me some examples of candidates with experience outside the ML remit and how this experience has helped and/or hindered them in becoming Mountain Leaders?
* How, if at all, do you feel that the number of QMDs prior to assessment influences a candidate’s chances of completion?
  * How much influence, if any, does the content/quality of candidate’s QMDs have on their chances of completion?
  * How, if at all, does the period over which a candidate accrues their QMDs affect their chances of completion?
* Are there any occasions where a candidate’s level of experience hasn’t been reflected by their result? For example, people with little experience passing or people with lots of experience being deferred or failed?
  * …and do you think that this was a fair reflection of them as a “mountain leader”
  * Why do you think some candidates with little experience are able to become Mountain Leaders whilst some more experienced aren’t?
* Some people talk about “tickers”, candidates that are “ticking off” the prerequisites. Is this something that you have noticed and if so, could you tell me about these “tickers”?
  * Are “tickers” obvious on Mountain Leader courses?
  * Could you give me some examples of the type of candidate who “tick” off QMDs?
  * Do you think that either “tickers” or “non-tickers” are more likely to complete than one another? Why do you think that is?
  * What differences, if any, do you think there are between "tickers" and "non-tickers"?


#### Personal Competency.

* Could you describe someone who is well prepared for their Mountain Leader assessment?
  * What proportion of candidates do you think are like this?
* In your experience, how good are candidates at judging their own abilities?
  * Could you give me some examples of how a discrepancy in perceived- and actual competency might affect a candidate at assessment?
    * Prompt: positively or negatively i.e., better or worse than they thought
  * If there are discrepancies, are they usually in the same direction across the board, or are some candidates better at one thing than they thought whilst also being worse at something else?
  * Which skills, if any, are discrepancies in perceived and actual ability most common in?
    * Prompt: either direction
  * …and which skills are these discrepancies the most significant in?
  * Do you think that the Mountain Leader assessment process helps candidates accurately gauge their own abilities?
* Do you think that there many candidates in your region who are ready for their assessment but don’t feel ready and therefore don’t book onto an assessment? 
  * Could you give me some examples of these candidates?
  * Why do you think it is that they don’t feel ready for their assessment?
  * What, if anything, do these candidates have in common?
    * Prompt: Sex, location, age
* ...and now what about the training process? Could you give me some examples of how a discrepancy in perceived competency and actual competency affect a candidate on a training course?
    * Prompt: positively or negatively
* Where do you see these discrepancies more, on training courses or at assessment?
  * Does the Mountain Leader training process helps candidates to accurately gauge their own abilities? If so, how does it do this?
* Is there anything about candidates’ experience and ability that you think is important but we haven’t spoken about?
* We have spoken about a number of different factors relating to candidate experiences’ and ability. Do you think that there any factors relating to a candidate’s experience and ability that are generally more important with regards to completion of the Mountain Leader award?


### Candidate Support.

In this section I am interested in the support that candidates receive from the people around them. This may be directly related to the Mountain Leader award but could also be in their day to day lives.

#### Training Staff/Centre.

* Could you describe some of the attitudes of course staff and directors toward the Mountain Leader award?
  * Prompt: positive or negative
* To what extent, if at all, do you think that course staff and directors feel candidates will become a part of their community by becoming Mountain Leaders?
  * …and to what extent do candidates feel that they will become part of this community by becoming Mountain Leaders?
  * ...and what effect do you think this might have?
* How, if at all, do completion rates vary by provider or individual assessor?
  * What makes their completion rates different?
    * Prompt: coaching, preparation, logbook checking, assessment style
* How, if at all, do completion rates vary by training course staff?
  * …and what do you think it is that makes their completion rates different?
* Can you give me some examples of course staff having a positive influence on candidates?
  * …and can you give me some examples of course staff having a negative influence on candidates?
* How, if at all, do training course debriefs vary by provider?
  * ...and what effect do you think these differences might have on candidates?
* Are some providers better at helping candidates create development plans than others? If so, what do they do differently?
  * ...and what effect do you think these differences might have on candidates?
* How, if at all, do assessment course reports vary by provider?
  * Do some providers give better feedback than others on course reports?
  * How does the content of this feedback vary?
  * ...and what effect do you think these differences might have on candidates?
* Do providers offer to help candidates between training and assessment?
  * Could you give me some examples of providers that do this and the help that they offer?
    * ...and what effect do you think that this help has on candidates?
    * Which types of candidate do you think that this help has the biggest effect on?
* How common, if at all, is it for candidates to contact providers between training and assessment?
  * What do they ask providers?


#### Instructor Support.

* Could you tell me a little bit about different course staff’s coaching and leadership of candidates during training courses? 
  * How, if at all, does this influence a candidate’s chances of completion? 
* Could you give me some examples of training staff’s coaching and/or leadership having positively influenced candidates?
* …and could you give me some examples of training staff’s coaching and/or leadership having had a negative impact on candidates?
* Different candidates might respond differently to the same leadership and/or coaching style. Can you give me some examples of how different candidates have responded to the leadership and coaching that they have received from course staff?
  * Prompt: Positive and negative
* Could you tell me a little bit about any training opportunities that are available to providers in your region?
  * Which providers make use of these opportunities?
  * ...and which ones don’t?
  * What do you think is different here?


#### Mentoring.

* To what extent do you think that there are mentoring opportunities available to candidates in your region?
* What do you think that this mentoring does for candidates?
* Do you think that candidates who have been mentored any more or less likely to become mountain leaders than those who have not been mentored?
* Who mentors candidates in your region?
  * Prompt: Formal & informal
* Would you consider centre assistant or fast track schemes to be mentoring?
  * …and what about candidates studying for an outdoor degree?
* How useful is it for Mountain Leader candidates to have a mentor?
* How, if at all, do candidates in your region benefit from mentoring?
* Can give me some examples of mentoring having had a negative influence on candidates?
  * Prompt: reliance on the mentor


#### Social Support.

The purpose of this next section is to try to find out about the help and support that Mountain Leader candidates may or may not receive in your region. This support can be directly related to the candidates Mountain Leader award but also to the rest of their lives. Candidates may receive many different types of support from a variety of people. I will give you a couple of examples, so that you understand what it is I would like you to tell me about.

Candidates might get support from a qualified instructor, providing feedback on technical skills. They might be part of a peer group that encourages them. They might have someone close to them whom they can turn to if they are feeling low. They might be offered financial support. These are some examples of the things that I would like you to tell me about. I am interested in any positive or negative effects of help and support of Mountain Leader candidates receive in your region.

* Do you understand what it is I would like you to talk to me about? Is there anything that you would like me to go over?
* In general, how important, if at all, do you think it is for candidates to be supported?
  * Do you think that there are any types of candidate who need more support that others? Why do you think that is?
  * ...and do you think that there are any types of candidates who don't need any support? And why do you think that is?
* Do you think that candidates are being given advice or guidance about the Mountain Leader award in your region?
  * If a candidate were to look for advice or guidance about the Mountain Leader award, who do you think that they would turn to?
    * Prompt: Qualified instructors, MT, providers, employers, friends? 
  * Which candidates, if any, need this support more than others?
    * Prompt: Sex, location, age, economic background
  * Are there any candidates who need more advice or guidance than they are receiving? If so, who do you think they are?
  * How much advice or guidance do successful candidates receive?
    * Is this different for candidates who don’t become Mountain Leaders?
  * Are there any candidates who have been adversely affected by the advice or guidance they have received from others? If so, who are they?
    * Where do they get this advice from?
* Could you give me some examples of candidates receiving help with practical matters in your region? E.g., financial assistance, help reducing workloads, help planning, refresher courses?
  * If a candidate were to look for practical help with the Mountain Leader award, who do you think that they would turn to?
    * Prompt: Family, friends, charities, MT, providers, employers?
  * Which candidates, if any, need this support more than other?
    * Prompt: Sex, location, age, economic background
  * Are there any candidates who need more practical help than they are receiving?
  * How much practical help do successful candidates receive?
    * Is this different for candidates who don’t become Mountain Leaders?
  * Are there any candidates who have been adversely affected by the practical help that they have received from others? If so, who are they?
    * Where do they get this advice from?
* Could you give me some examples of help that candidates receive in dealing with how they feel about the Mountain Leader award? For example, this could be someone helping a candidate with pre-assessment nerves or general encouragement.
  * If a candidate were to look for esteem support, who do you think that they would turn to?
    * Prompt: Friends, family, mentor
  * Which candidates, if any, need this support more than others?
    * Prompt: Sex, location, age, economic background
  * Are there any candidates who are not receiving enough help in dealing with how they feel about the Mountain Leader award?
  * How much help in dealing with their feelings towards the Mountain Leader award do successful candidates receive?
    * Is this different for candidates who don’t become Mountain Leaders?
  * Are there any candidates who have been adversely affected by the help in dealing with their feelings toward the Mountain Leader award that they have received from others?
* Could you give me some examples of help that candidates receive in dealing with personal issues relating to their life and future? For example, this could be someone helping them when they feel low, or someone that they can bounce ideas off.
  * Who do candidates turn to for this support?
    * Prompt: Friends, family, partners
  * Which candidates, if any, need this support more than others?
    * Prompt: Sex, location, age, economic background
  * Are there any candidates that need more help in dealing with personal issue than they are receiving?
  * How much help dealing with personal issues do successful candidates receive?
    * Is this different for candidates who don’t become Mountain Leaders?
  * Are there any candidates who have been adversely affected by the help in dealing with personal issues that they have received from others? If so, who are they?
    * Where do they get this advice from?
* Could you tell me about how Mountain Leader award candidates support each other? Or do they prepare in isolation of each other?
  * How much help from other candidates do successful candidates receive?
    * Is this different for candidates who don’t become Mountain Leaders?
  * Which candidates does this support affect more than others? Why do you think that is? 
  * Are there any issues that candidates are more willing to tackle amongst themselves rather than with Mountain Training or course providers? 
    * What sort of things are they and why do you think that is? 
* We have spoken about a number of different types of support that is available to candidates, how much of this support do you think that they receive from the MTA? 
* Could you tell me how important, if at all, you think it is for candidates to be supported by others as they progress through the Mountain Leader award?
  * Do you think that any of these support types (emotional, esteem, tangible, and informational) as more important than any of the others?
* How important, if at all, do you think that providers feel that it is for candidates to be supported through the Mountain Leader award?
  * Do you think that they see any of these support types (emotional, esteem, tangible, and informational) as more important than any of the others?
* …and how important do you think that candidates feel it is that they are supported through the Mountain Leader award?
* Do you think that there are any groups of candidates who need or want more support than others? Maybe more of one type in particular?
* Do you see any differences in candidates who expect more support in general and candidates who seek out more support?
* Could you tell me a little bit about how, if at all, individual differences might affect the influence of different support types?
  * Examples of types of candidates who are impacted more or less by different types?
* Is there anything about candidate support that you think is important but we haven’t spoken about?
* We have spoken about a number of different factors relating to candidate support. Do you think that there any factors relating to candidate support that are generally more important with regards to completion of the Mountain Leader award?

#### End.

* Is there anything in relation to: Candidate Ability or Support that we have not covered but you think is relevant?
* Is there anything unique to your region, that we have not discussed, that perhaps makes it different to the others? 
* Is there anything we may have missed that you feel would be important? For example, are there factors outside of the MT framework that would give us some insight into completion rates in your region? Even something that you don’t quite understand or can’t quite explain, something you’d almost feel might sound silly, but somehow you feel is relevant?
* Thank you for your time today
