# Chapter 3 Initial Classification Rates {#pra-supp-info}

```{r g5-male-gta18m-train-models}
G5_male_GTA18m_train_PRA %>% 
  filter(!str_detect(Dataset, "4s")) %>% 
  mutate(Rating = case_when(between(median, 0, 60) ~ "Poor",
                            between(median, 60, 70) ~ "Modest",
                            between(median, 70, 80) ~ "Good",
                            between(median, 80, 90) ~ "Very Good",
                            between(median, 90, 100) ~ "Excellent"),
         Dataset = str_replace_all(Dataset, "_", " ")) %>% 
  select(-c(mean, median)) %>% 
  kable(caption = "Group 5 male candidates getting to assessment within 18 months of training, initial classification, training model performance.", digits = 2, booktab = TRUE, longtable = TRUE, linesep = "") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = FALSE, 
                latex_options = c("HOLD_position", "repeat_header", "striped"), 
                font_size = 10)
```


```{r g5-female-gta18m-train-models, eval=TRUE}
G5_female_GTA18m_PRA %>% 
  filter(!str_detect(Dataset, "4s")) %>% 
  mutate(Rating = case_when(between(median, 0, 60) ~ "Poor",
                            between(median, 60, 70) ~ "Modest",
                            between(median, 70, 80) ~ "Good",
                            between(median, 80, 90) ~ "Very Good",
                            between(median, 90, 100) ~ "Excellent"),
         Dataset = str_replace_all(Dataset, "_", " ")) %>% 
  select(-c(mean, median)) %>%
  kable(caption = "Group 5 female candidates getting to assessment within 18 months of training, initial classification, training model performance.", digits = 2, booktab = TRUE, longtable = TRUE, linesep = "") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = FALSE, 
                latex_options = c("HOLD_position", "repeat_header", "striped"),
                font_size = 10)
```


```{r g5-zsex-ftp-train-models, eval=TRUE}
G5_zsex_ftp_train_PRA %>% 
  mutate(Rating = case_when(between(median, 0, 60) ~ "Poor",
    between(median, 60, 70) ~ "Modest",
    between(median, 70, 80) ~ "Good",
    between(median, 80, 90) ~ "Very Good",
    between(median, 90, 100) ~ "Excellent"),
    Dataset = str_replace_all(Dataset, "_", " ")) %>% 
  select(-c(mean, median)) %>% 
  kable(caption = "Group 5 passing first time, initial classification, training model performance. Data standardised within sex.", digits = 2, booktab = TRUE, linesep = "") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = FALSE, 
                latex_options = c("basic", "HOLD_position", "striped"),
                font_size = 10)
```

